# Generated by Django 5.0.6 on 2024-06-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="josaaTable",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Institute", models.CharField(max_length=100)),
                ("Seat_Type", models.CharField(max_length=20)),
                ("Gender", models.CharField(max_length=30)),
                ("Opening_Rank", models.IntegerField()),
                ("Closing_Rank", models.IntegerField()),
                ("Year", models.IntegerField()),
                ("Round_No", models.IntegerField()),
                ("Programme", models.CharField(max_length=100)),
                ("Duration_Yrs", models.IntegerField()),
                ("Discipline", models.CharField(max_length=100)),
            ],
        ),
    ]
