# Generated by Django 5.0.6 on 2024-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institute", models.CharField(max_length=400)),
                ("Seat_type", models.CharField(max_length=20)),
                ("Gender", models.CharField(max_length=30)),
                ("Opening_rank", models.CharField(max_length=10)),
                ("Closing_rank", models.CharField(max_length=10)),
                ("Year", models.IntegerField()),
                ("Round", models.IntegerField()),
                ("Program_name", models.CharField(max_length=150)),
                ("Program_duration", models.IntegerField()),
                ("Program_type", models.CharField(max_length=100)),
            ],
        ),
    ]
