# Generated by Django 5.0.6 on 2024-06-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="josaatable",
            old_name="Seat_Type",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="josaatable",
            old_name="Discipline",
            new_name="Course",
        ),
        migrations.RenameField(
            model_name="josaatable",
            old_name="Round_No",
            new_name="Round",
        ),
    ]
